export const ADD_TODO_TASK = "ADD_TODO_TASK";
export const COMPLETED_TASK = "TASK_COMPLETED";
export const REMOVE_TODO_TASK = "REMOVE_TODO_TASK";
export const REMOVE_ALREADY_DONE_TASK = "REMOVE_ALREADY_DONE_TASK";
